version: '3.8'

services:
  fyp-dashboard:
    image: ghcr.io/dylangore-fyp/dashboard:latest
    container_name: fyp-dashboard
    build:
      context: .
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8080:80
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
