name: 'build'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build & Publish Docker Image to GHCR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code from GitHub'
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Images
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/arm64/v8\
            --output "type=image,push=true" \
            --file ./Dockerfile
